source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, "8.0"


target :FZLibDemo do
    pod "FZLib", :path => "../"  #spec file path
end

target :FZLibDemoTests do
    pod "FZLib", :path => "../"

    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
end
